name: Genshin check-in

on:
  # Allow manual start
  workflow_dispatch:
  # Run job on 08:15UTC/00:15CST daily
  schedule:
  - cron: "15 8 * * *"

jobs:
  # check-in now
  check-in:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/gi-check-in
      with:
        id:    ${{ secrets.MHYACID }}
        uuid:  ${{ secrets.MHYUUID }}
        token: ${{ secrets.MHYTOKEN }}
# vim: ft=yaml:ts=2:et:
