name: Publish Docker image

on:
  push:
    branches:
    - master
    paths:
    - '**.py'
    - Dockerfile
    - poetry.lock
    - pyproject.toml

  release:
    types:
    - published

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: |
          latest=false

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ${{ steps.meta.outputs.tags }}
          ghcr.io/${{ github.repository }}:latest
        labels: ${{ steps.meta.outputs.labels }}

# vim: ft=yaml:ts=2:et:
